### ISSUE TITLE
Material Design in Dashboard.hbs for Selection tabs

### ISSUE THREAD

**Issue by utkarshsingh99** [utkarshsingh99/ClubComing#12]
Icon needs to be added next to Selected, Shortlisted, Rejected, All. 
If possible, Hamburger menu can be constructed for better display.

**Comment by PseudoNerd** [comment]
Would like to take this up.

**Comment by utkarshsingh99** [comment]
Sure, go ahead! All the best

**Comment by utkarshsingh99** [comment]
Issue resolved in #28 
Great job!
