### ISSUE TITLE
Change Background Image of Log In Page

### ISSUE THREAD

**Issue by utkarshsingh99** [utkarshsingh99/ClubComing#22]
**Describe the new UI**
Currently, the background is a little blur. Replacethe BG-Image to a clear, HD photo. It should be generalised and not any theme-based photo like a Marvel superhero pic, etc. Any pic that expresses openness and a happy ambience would be fine.

**Technologies Required**: HTML, CSS

**Comment by utkarshsingh99** [comment]
Okay, assigned.

**Comment by Sweta271097** [comment]
Hello, 

Can I also change the front end of the log in page?

**Comment by Sweta271097** [comment]
Hello, 

Can I  also work on the front end of the login page?

**Comment by utkarshsingh99** [comment]
Yeah sure. Just don't alter the functionality. And make sure you upload screenshots while making the PR in the comments
