### ISSUE TITLE
Make Sign Up Page (Front-End)

### ISSUE THREAD

**Issue by utkarshsingh99** [utkarshsingh99/ClubComing#33]
**Is your feature request related to a problem? Please describe.**
We need to open this site for every club anywhere. Henceforth, we need a sign up page for clubs.

**Describe the solution you'd like**
Only the front-end needs to be designed. The page needs to have the following: 
1. Name of Club,
2. Password,
3. Confirm Password
4. Sign Up button

Make a JS Code to cross-check the values in 'Password' and 'Confirm Password' are the same after clicking on 'Sign Up' button 

**Technologies you need to use**
HTML, CSS, JavaScript

**Comment by Sweta271097** [comment]
Hello, 

@utkarshsingh99  I would really like to work on this issue.

**Comment by utkarshsingh99** [comment]
Sure, go ahead

**Comment by utkarshsingh99** [comment]
Actually someone just made a PR for it. Sorry 
#38
