### ISSUE TITLE
Add button in Home Page

### ISSUE THREAD

**Issue by utkarshsingh99** [utkarshsingh99/ClubComing#35]
**Is your feature request related to a problem? Please describe.**
Need a new button which says, 'Not a registered club? Sign Up'

**Describe the solution you'd like**
You are free to locate the button anywhere in the web page. Make sure it's visible. For now, no JS functionality or redirect is needed.

**Technologies Needed**
HTML, CSS

**Comment by Sweta271097** [comment]
Hello, 

@utkarshsingh99  Can I take up this issue?

**Comment by utkarshsingh99** [comment]
Sure, go ahead

**Comment by utkarshsingh99** [comment]
The button has already been added, but it would be great if you could place it some place unique. Since you'd designed this page yourself

**Comment by Sweta271097** [comment]
@utkarshsingh99 Okay, I'll see.

**Comment by Sweta271097** [comment]
@utkarshsingh99 Okay, I will add it.

**Comment by utkarshsingh99** [comment]
Merged PR
