### ISSUE TITLE
Make the database store Roll Number IN CAPS

### ISSUE THREAD

**Issue by utkarshsingh99** [utkarshsingh99/ClubComing#7]

**Comment by utkarshsingh99** [comment]
Do you have the lodash module installed?

**Comment by capedcrusader23** [comment]
i have but i think it is not included in codebase

**Comment by utkarshsingh99** [comment]
It is there in package.json. Can you show me what's the error?

**Comment by capedcrusader23** [comment]
This is the error

![image](https://user-images.githubusercontent.com/37747717/49328388-e7a3bd00-f595-11e8-8c8b-0785576f328d.png)

lodash is not required here
![image](https://user-images.githubusercontent.com/37747717/49328393-02763180-f596-11e8-9124-52821cf87b08.png)

**Comment by utkarshsingh99** [comment]
Include the lodash module there. Look at the Line 81. It is in fact, using lodash. 
You just need to include that line. 
Thanks for pointing the error out!

**Comment by capedcrusader23** [comment]
ok will do that

**Comment by utkarshsingh99** [comment]
Feel free to make a pull request for any pointed out bugs or issues, though.

**Comment by capedcrusader23** [comment]
Check pr

**Comment by utkarshsingh99** [comment]
#17 Issue resolved
