### ISSUE TITLE
Design CV Page as LaTeX backup

### ISSUE THREAD

**Issue by utkarshsingh99** [utkarshsingh99/ClubComing#9]
In case LaTeX code fails, a CV page can be given to the Clubs to view the CV whose data will be directly fetched from the Database

**Technologies you need to know for this issue**:
1. HTML, CSS, JS to just design the front end template of the CV page.
**OR**
2. Node to just make a seperate request to render this page.
**OR**
3. 1 + 2 if you want to completely solve this isse. Else we can break this down into 2 different issues for someone else to solve the other one.

**Comment by utkarshsingh99** [comment]
Sure, go ahead!

**Comment by Sweta271097** [comment]
Hello, 
Can I get a rough idea about how do you want the CV page to look like?

**Comment by utkarshsingh99** [comment]
You only have the following constraints:
1. There should be a bold name and a photo of the person visible on the page such that the first thing you see when you open the page are those two.
2. All the questions that are listed in the CV PDF, all the personal info about the person should be listed in the CV page. Nothing should be omitted

These are the only constraints. About the design, I'm giving you complete freedom to decide what looks best. Think what an interviewer would like. 
Good Luck!

**Comment by utkarshsingh99** [comment]
@Sweta271097 Are you done with this issue?

**Comment by Sweta271097** [comment]
@utkarshsingh99  Yes, I'm done. Will make a PR in sometime.

**Comment by Sweta271097** [comment]
@utkarshsingh99 Hello,

I have an html and css file and I am having a little problem converting the html file to a hbs file. Could you help me with it?

**Comment by utkarshsingh99** [comment]
Just rename your html file to hbs (change the extension).
That's it

**Comment by Sweta271097** [comment]
@utkarshsingh99 Thank you.

**Comment by Sweta271097** [comment]
@utkarshsingh99 Made a PR.

**Comment by utkarshsingh99** [comment]
Done in #25 
Good job!
